# Generated by Django 3.1.2 on 2020-10-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(default='N/A', max_length=50)),
                ('nombreCiclos', models.IntegerField(default=120)),
                ('codigoCarrera', models.CharField(default='N/A', max_length=10)),
                ('numeroDocentes', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField(default=5)),
                ('nombre', models.CharField(default='N/A', max_length=10)),
                ('numeroEstudiantes', models.IntegerField(default=5)),
                ('carrera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='holamundo.carrera')),
            ],
        ),
    ]
